name: nightly
on:
  # run these tests either manually or on schedule
  workflow_dispatch:
  schedule:
    # run these tests every day
    - cron: '0 23 * * *'

jobs:
  test:
    # use the reusable workflow to check out the code, install dependencies
    # and run the Cypress tests
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      env: 'grepTags=@nightly'
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           env: 'grepTags=@nightly'
