name: scrape
on:
  # run these tests either manually or on schedule
  workflow_dispatch:
  schedule:
    # run these tests every day
    - cron: '0 23 * * *'

env:
  DEBUG: cy-grep,@cypress/github-action

jobs:
  test:
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      # pass Cypress.env variable --env
      env: 'grepTags=@scrape'
